### 1. 登录并获取 Token (点击左侧的绿色箭头运行)
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "rain",
  "password": "lidagezuishuai66"
}

### 2. 拿着 Token 去获取收货地址 (记得把下面的 YOUR_ACCESS_TOKEN 替换掉)
GET http://127.0.0.1:8000/api/addresses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMTMxMDE1LCJpYXQiOjE3NzMxMzA3MTUsImp0aSI6IjFiNWMwYTk1YTllMjQ4YjZhYTA5YWJiZjJiNWU2MGQzIiwidXNlcl9pZCI6IjEifQ.vLx2-gVrvB7JdREfmIrC0_s3wURoDZaZPQoXAVFVMlg