### 1. 登录并获取 Token (点击左侧的绿色箭头运行)
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "rain",
  "password": "lidagezuishuai66"
}

### 2. 拿着 Token 去获取收货地址 (记得把下面的 YOUR_ACCESS_TOKEN 替换掉)
GET http://127.0.0.1:8000/api/addresses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMTMyNjAzLCJpYXQiOjE3NzMxMzIzMDMsImp0aSI6IjRkYzNkYWEzOTRmMjQzZmFhYzIxY2NhNDI5MjFjNjhmIiwidXNlcl9pZCI6IjEifQ.sqhqUHWa73uwznLroH_0VzoWTgRI5DwOQgwEDIJMgtg

### 3. 加入购物车测试
POST http://127.0.0.1:8000/api/cart/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMTMyNjAzLCJpYXQiOjE3NzMxMzIzMDMsImp0aSI6IjRkYzNkYWEzOTRmMjQzZmFhYzIxY2NhNDI5MjFjNjhmIiwidXNlcl9pZCI6IjEifQ.sqhqUHWa73uwznLroH_0VzoWTgRI5DwOQgwEDIJMgtg
Content-Type: application/json

{
  "product": 1,
  "nums": 1
}


### 4. 一键结算！(记得在Bearer后面换上你最新获取的Token！)
POST http://127.0.0.1:8000/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMTMyNjAzLCJpYXQiOjE3NzMxMzIzMDMsImp0aSI6IjRkYzNkYWEzOTRmMjQzZmFhYzIxY2NhNDI5MjFjNjhmIiwidXNlcl9pZCI6IjEifQ.sqhqUHWa73uwznLroH_0VzoWTgRI5DwOQgwEDIJMgtg
Content-Type: application/json

{
  "address": "山东省青岛市崂山区松岭路238号中国海洋大学",
  "signer_name": "李雨润",
  "signer_mobile": "13663591937"
}