# Generated by Django 5.2.12 on 2026-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_orderinfo_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待支付'), ('shipping', '待发货'), ('receiving', '待收货'), ('success', '已完成'), ('closed', '已取消')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
